data:
    batch_size: 16
    rot: 15
    root: ~                     # None: [will be expand as ~/datasets/scene15]
    vgg: False
    scale_ratio: 0.7
    val_crop: True

model:
    name: efficientnet_b3_k
    kwargs:
        bn_mom: 0.9
        dropout_rate: 0.25      # b0b1: 0.2, b2b3: 0.3, b4b5: 0.4, b6b7: 0.5
    ema_mom: 0.999

train:
    epochs: 300
    lr: [0.01, 0.02, 0.04, 0.08,    0.1, 0.2, 0.4, 0.8]
    wd: 2e-5
    nowd: True
    ls_ratio: 0.05
    grad_clip: 4
    # desc: [will be auto assigned in runtime]

