data:
    batch_size: 32
    wh: [0.6, 0.4]
    scale_ratio: [0.6, 0.4]
    sharp: [0.6, 1.0]
    trans: [0.15, 0.35]
    rot: [15, 25]
    jitter: [0.25, 0.45]
    root: ~                     # None: [will be expand as ~/datasets/scene15]
    vgg: False
    val_crop: True

model:
    name: efficientnet_b3_k
    kwargs:
        bn_mom: 0.9
        dropout_rate: [0.5, 0.6, 0.7, 0.8]      # b0b1: 0.2, b2b3: 0.3, b4b5: 0.4, b6b7: 0.5
    ema_mom: 0.999

train:
    epochs: 400
    lr: 0.08
    wd: 1e-3
    nowd: True
    ls_ratio: 0.05
    mix: 0.2
    grad_clip: 4
    # desc: [will be auto assigned in runtime]

